name: Deploy Node.js App to VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            set -e

            echo "================================"
            echo "Cloning repository..."
            echo "================================"

            git clone https://github.com/perfectdash/nodejs-application.git


            cd nodejs-application

            echo "================================"
            echo "Building Docker image..."
            echo "================================"
            
            docker build -f DockerFile -t nodejs-app . 
            

            echo "================================"
            echo "Running Docker container..."
            echo "================================"

            docker run -d -p 3000:3000 --name nodejs-app-container nodejs-app

            echo "================================"
            echo "File Cleanup thing ... "
            echo "================================"

            rm -rf nodejs-application
            

